#!/usr/bin/env python3

import json
import ipaddress
import re
import requests

WPT_URL = "https://raw.githubusercontent.com/web-platform-tests/wpt/33e4ac09029c463ea6ee57d6f33477a9043e98e8/url/resources/urltestdata.json"

SKIP_TESTS = (
    "http://\uff10\uff38\uff43\uff10\uff0e\uff10\uff12\uff15\uff10\uff0e\uff10\uff11",
    "file://xn--/p",
)


def main():
    surrogate_re = re.compile(r"[\uD800-\uDFFF]")
    tests = []
    resp = requests.get(WPT_URL)
    for elem in resp.json():
        if isinstance(elem, str):
            tests.append(elem)
        else:
            if elem["input"] not in SKIP_TESTS and not surrogate_re.search(
                elem["input"]
            ):
                if (
                    "hostname" in elem
                    and len(elem["hostname"]) > 0
                    and elem["hostname"][0] == "["
                    and elem["hostname"][-1] == "]"
                ):
                    try:
                        address = ipaddress.IPv6Address(elem["hostname"][1:-1])
                        elem["hostname"] = address.exploded
                    except ipaddress.AddressValueError:
                        pass
                tests.append(elem)
    print(json.dumps(tests, indent=2, ensure_ascii=True))


if __name__ == "__main__":
    main()
