Import('env')

env['CCFLAGS'] += ' -fPIC'

env['CPPPATH'] = [ '#include' ]

env.ParseConfig(env['CONFIG_PARSER'])

env.StaticLibrary(
    'nwutil',
    [
        'nwutil.c',
        'uri.c',
    ],
)
